apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: avatars

resources:
  - ../../base
  - storage-pvc.yaml
  - alias.yaml
  - ingress.yaml

patches:
  - path: patch-api-storage.yaml
