apiVersion: v1
kind: Service
metadata:
  name: avatars-generator-web
spec:
  selector:
    app: avatars-generator-web
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
