name: Continuous Integration

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run Backend Tests
        run: make test-backend

      - name: Run Frontend Tests
        run: make test-frontend

  security-scan:
    name: Build & Trivy Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for API
        id: meta-api
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/cf-avatars-generator-api
          tags: |
            type=edge,branch=develop
            type=sha,format=short,prefix=sha-

      - name: Build API image for Trivy scan
        uses: docker/build-push-action@v5
        with:
          context: ./api
          load: true
          tags: local-api:test
          cache-from: type=gha

      - name: Run Trivy vulnerability scanner on API
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'local-api:test'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL'



      - name: Extract metadata (tags, labels) for Web
        id: meta-web
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/cf-avatars-generator-web
          tags: |
            type=edge,branch=develop
            type=sha,format=short,prefix=sha-

      - name: Build Web image for Trivy scan
        uses: docker/build-push-action@v5
        with:
          context: ./web
          load: true
          tags: local-web:test
          cache-from: type=gha

      - name: Run Trivy vulnerability scanner on Web
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'local-web:test'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL'



  kustomize-validation:
    name: Kustomize Syntax Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate Staging Manifests
        run: kubectl kustomize k8s/overlays/staging > /dev/null
