apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: avatars-generator

resources:
  - ../../base
  - alias.yaml

patches:
  - path: patch-api-storage.yaml

secretGenerator:
  - name: avatars-generator-secret
    envs:
      - .env.secret

images:
  - name: ghcr.io/mati2173/cf-avatars-generator-api
    newTag: "1.0.0"
  - name: ghcr.io/mati2173/cf-avatars-generator-web
    newTag: "1.0.0"
