apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: avatars-generator-data
  namespace: avatars-generator
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 1Gi
